name: CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js version 18 (or the version you prefer)
          cache: 'npm'      # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Start development server (optional)
        run: npm start
        env:
          BROWSER_SYNC_PORT: 7777  # Optional: Set the port for browser-sync
